spring.application.name=event-reservation

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_db?options=-c%20timezone=UTC
spring.datasource.username=admin
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#After getting error
#spring.datasource.hikari.connection-init-sql=SET timezone = 'UTC';